export enum ToolName {
    Pencil = 0,
    Brush = 1,
    Line = 2,
    Eraser = 3,
    Rectangle = 4,
    Ellipse = 5,
    Polygon = 6,
    PaintBucket = 7,
    Eyedropper = 8,
    SelectionRectangle = 9,
    SelectionEllipse = 10,
    Spray = 11,
    Text = 12,
    Feather = 13,
    Stamp = 14,
}
