export enum ToolShortcut {
    Pencil = 'c',
    Brush = 'w',
    Line = 'l',
    Rectangle = '1',
    Ellipse = '2',
    Polygon = '3',
    Eraser = 'e',
    PaintBucket = 'b',
    Eyedropper = 'i',
    SelectionRectangle = 'r',
    SelectionEllipse = 's',
    Feather = 'p',
    Text = 't',
    Spray = 'a',
    Stamp = 'd',
    Clipboard = 'ctrl+c',
}
